amcl:
  ros__parameters:
    use_sim_time: true
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    scan_topic: "/ultrasonic_front_left"  # Full topic name
    min_particles: 100
    max_particles: 5000
    resample_interval: 1
    transform_tolerance: 1.0
    recovery_alpha_slow: 0.0
    recovery_alpha_fast: 0.0
    initial_pose_x: 0.0
    initial_pose_y: 0.0
    initial_pose_a: 0.0

map_server:
  ros__parameters:
    use_sim_time: true
    yaml_filename: "/home/kshitij/dev_ws/src/my_bot/map/grid_map.yaml"

planner_server:
  ros__parameters:
    use_sim_time: true
    expected_planner_frequency: 20.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "smac_planner/SmacPlanner2D"

controller_server:
  ros__parameters:
    use_sim_time: true
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"

bt_navigator:
  ros__parameters:
    use_sim_time: true
    behavior_tree_xml: "/home/kshitij/dev_ws/src/my_bot/bt/custom_bt.xml"

behavior_server:
  ros__parameters:
    use_sim_time: true

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: true
      global_frame: "odom"
      robot_base_frame: "base_link"
      update_frequency: 5.0
      publish_frequency: 2.0
      width: 3   # ✅ Integer
      height: 3  # ✅ Integer (fixes your crash)
      resolution: 0.05
      rolling_window: true
      plugins: ["obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: ultrasonic
        ultrasonic:
          topic: "/ultrasonic_front_left"
          sensor_frame: "ultrasonic_frame"  # Replace with your actual sensor frame
          data_type: "LaserScan"
          marking: true
          clearing: true
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.5

global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: true
      global_frame: "map"
      robot_base_frame: "base_link"
      update_frequency: 5.0
      publish_frequency: 2.0
      resolution: 0.05
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: ultrasonic
        ultrasonic:
          topic: "/ultrasonic_front_left"
          sensor_frame: "front_left_sensor_link"  # Replace with your actual sensor frame
          data_type: "LaserScan" #
          marking: true
          clearing: true
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.5
